/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ericocosta.conectards_aws;

import br.com.ericocosta.conexao.Impl.BancoJdbc;
import br.com.ericocosta.conexao.Repositorio.Crud_Repositorio;
import br.com.ericocosta.dados_banco.Dado;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.Alert;
import javafx.scene.control.SelectionMode;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author erico
 */
public class JanelaApp extends javax.swing.JFrame {

    private static boolean ehsalvar = true;
    /**
     * Creates new form JanelaApp
     * @param title
     */
    public JanelaApp(String title) {
        setTitle(title);
//      tListaMsg.getSelectionModel().setSelectionMode(SelectionMode.SINGLE);
        initComponents(); 
        setSize(800,400);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tListaMsg = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tMensagem = new javax.swing.JTextArea();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setName("tela"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tListaMsg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Mensagem"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tListaMsg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tListaMsgMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tListaMsg);

        jLabel1.setLabelFor(tMensagem);
        jLabel1.setText("Mensagem");
        jLabel1.setName("lmensagem"); // NOI18N

        tMensagem.setColumns(20);
        tMensagem.setRows(1);
        tMensagem.setTabSize(4);
        tMensagem.setToolTipText("");
        tMensagem.setName("mensagem"); // NOI18N
        jScrollPane2.setViewportView(tMensagem);

        btnSalvar.setText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });

        btnApagar.setText("Apagar");
        btnApagar.setEnabled(false);
        btnApagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnApagarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btnApagar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar)
                    .addComponent(btnApagar))
                .addContainerGap(234, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
        // TODO add your handling code here:
        Crud_Repositorio<Dado> crud_Dados = new BancoJdbc();
        Dado dadoMensagem = new Dado();
        dadoMensagem.setMensagem(tMensagem.getText());
        if(ehsalvar){
            try{
                crud_Dados.Incluir(dadoMensagem);
                tMensagem.setText("");
                carregaTabelaDados();
            } catch (IOException | SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE, null);
            }
        }else{
            try{
                int idMsg = Integer.parseInt( tListaMsg.getValueAt(tListaMsg.getSelectedRow(),0).toString());
                dadoMensagem.setId(idMsg);
                crud_Dados.Alterar(dadoMensagem);
                btnSalvar.setText("Salvar");
                tMensagem.setText("");
                btnCancelar.setEnabled(ehsalvar);
                btnApagar.setEnabled(ehsalvar);
                carregaTabelaDados();
                ehsalvar = true;
            }
            catch (Exception ex){
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE, null);                
            }
        }
    }//GEN-LAST:event_btnSalvarMouseClicked

    private void btnApagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApagarMouseClicked
        // TODO add your handling code here:
        Crud_Repositorio<Dado> crud_Dados = new BancoJdbc();
        Dado dadoMensagem = new  Dado();
//       contatoselecionado = tListaMsg.getSelectedRow()
        try {
                int idMsg = Integer.parseInt( tListaMsg.getValueAt(tListaMsg.getSelectedRow(),0).toString());
                dadoMensagem.setId(idMsg);
                btnCancelar.setEnabled(ehsalvar);
                btnApagar.setEnabled(ehsalvar);
                btnSalvar.setText("Salvar");
                tMensagem.setText("");
                crud_Dados.Excluir(dadoMensagem);
                carregaTabelaDados();
                ehsalvar = true;            
        } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE, null);
        }
    }//GEN-LAST:event_btnApagarMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
                carregaTabelaDados();
        
    }//GEN-LAST:event_formWindowOpened

    private void tListaMsgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tListaMsgMouseClicked
        // TODO add your handling code here:
        int linha =  tListaMsg.getSelectedRow();
        tMensagem.setText(tListaMsg.getValueAt(linha, 1).toString());
        btnSalvar.setText("Alterar");
        btnCancelar.setEnabled(ehsalvar);
        btnApagar.setEnabled(ehsalvar);
        ehsalvar = false;
  
    }//GEN-LAST:event_tListaMsgMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        // TODO add your handling code here:
        btnSalvar.setText("Salvar");
        tMensagem.setText("");
        carregaTabelaDados();
        btnCancelar.setEnabled(ehsalvar);
        btnApagar.setEnabled(ehsalvar);
        ehsalvar = true;
    }//GEN-LAST:event_btnCancelarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
////                new JanelaApp().setVisible(true);
//            }
//        });
        
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
////                new JanelaApp().setVisible(true);
//            }
//        });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tListaMsg;
    private javax.swing.JTextArea tMensagem;
    // End of variables declaration//GEN-END:variables

    private void carregaTabelaDados() {
            Crud_Repositorio<Dado> selecionaDados = new BancoJdbc();
//            List<Dado> listaMensagens;
            
            tListaMsg.getColumnModel().getColumn(0).setPreferredWidth(5);
            try{
                DefaultTableModel listaMensagens = (DefaultTableModel) tListaMsg.getModel();
                listaMensagens.setNumRows(0);
                for (Dado lm : selecionaDados.Selecionar()) {
                    listaMensagens.addRow(new Object[]
                    {
                        lm.getId(),
                        lm.getMensagem()
                    });
                }
//                TableRowSorter sorter = new TableRowSorter(listaMensagens);
//                tListaMsg.setRowSorter(sorter);
//                sorter.toggleSortOrder(0);
            }
            catch(Exception ex ){
                    JOptionPane.showMessageDialog(null,"Erro ao carregar os dados"+ex,"ERRO",JOptionPane.ERROR_MESSAGE);
                    btnSalvar.setEnabled(false);
            }
    }
}
